apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: owaspten
  name: owaspten
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    run: owaspten
status:
  loadBalancer: {}
