apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: owaspten 
  name: owaspten
spec:
  replicas: 1
  selector:
    matchLabels:
      run: owaspten
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: owaspten
    spec:
      containers:
      - image: mcgonagle/owaspten
        name: owaspten
        resources: {}
status: {}
