name: build
on: workflow_dispatch
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Scan Remote Image
        uses: neuvector/scan-action@main
        with:
          debug: true
          image-registry: docker.io
          image-registry-username: ${{ secrets.REGISTRYUSERNAME }}
          image-registry-password: ${{ secrets.REGISTRYPASSWORD }}
          image-repository: mcgonagle/owaspten
          image-tag: latest
          min-high-cves-to-fail: "1"
          min-medium-cves-to-fail: "1"
